parameters:
    ongr_magento.modifier.product.class: ONGR\MagentoConnectorBundle\Modifier\ProductModifier

services:
    ongr_magento.modifier.product:
        class: %ongr_magento.modifier.product.class%
        arguments:
            - %ongr_demo.magento.import.store_id%
            - %ongr_demo.magento.import.shop_id%
        tags:
            - { name: 'ongr_connections.doctrine.modifier', type: 'product' }
